# Generated by Django 6.0.4 on 2026-05-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_userreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='title',
        ),
    ]
