# Generated by Django 6.0.4 on 2026-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expenses_description_remove_expenses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
