# Generated by Django 6.0.4 on 2026-05-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_color_alter_user_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
