from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from django.utils import timezone


CREATOR_NAME = "Ibrahim Hamdouna"
APP_NAME = "My Expenses"
GITHUB_URL = "https://github.com/ibrahim-hamdouna"


def create_excel_report(expenses, total):
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Expenses"
    sheet.append(["Description", "Category", "Date", "Amount"])
    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1B4332")
    for expense in expenses:
        sheet.append([expense.description or "-", expense.category.name if expense.category else "No category", expense.date, float(expense.amount)])
    sheet.append(["", "", "Total", float(total)])
    sheet.cell(sheet.max_row, 3).font = Font(bold=True)
    sheet.cell(sheet.max_row, 4).font = Font(bold=True)
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = f"A1:D{max(sheet.max_row - 1, 1)}"
    for cell in sheet["C"][1:-1]:
        cell.number_format = "yyyy-mm-dd"
    for cell in sheet["D"][1:]:
        cell.number_format = '$#,##0.00'
    for index, width in enumerate([35, 22, 15, 15], start=1):
        sheet.column_dimensions[get_column_letter(index)].width = width

    info = workbook.create_sheet("Report Information")
    info.append(["Report Information"])
    info.append(["Application", APP_NAME])
    info.append(["Developed by", CREATOR_NAME])
    info.append(["Generated on", timezone.localtime().strftime("%Y-%m-%d %H:%M")])
    info["A1"].font = Font(bold=True, size=14, color="FFFFFF")
    info["A1"].fill = PatternFill("solid", fgColor="1B4332")
    info.column_dimensions["A"].width = 20
    info.column_dimensions["B"].width = 30
    info["B3"].hyperlink = GITHUB_URL
    info["B3"].style = "Hyperlink"
    output = BytesIO()
    workbook.save(output)
    return output.getvalue()


def create_pdf_report(expenses, total, start_date=None, end_date=None):
    output = BytesIO()
    document = SimpleDocTemplate(output, pagesize=landscape(A4), leftMargin=15 * mm, rightMargin=15 * mm, topMargin=15 * mm, bottomMargin=20 * mm, title="Expense Report", author=CREATOR_NAME, creator=APP_NAME)
    styles = getSampleStyleSheet()
    period = f"{start_date or 'Beginning'} to {end_date or 'Today'}" if start_date or end_date else "All dates"
    story = [Paragraph("Expense Report", styles["Title"]), Paragraph(f"Period: {period}", styles["Normal"]), Spacer(1, 8)]
    data = [["Description", "Category", "Date", "Amount"]]
    for expense in expenses:
        data.append([Paragraph(expense.description or "-", styles["BodyText"]), expense.category.name if expense.category else "No category", expense.date.strftime("%Y-%m-%d"), f"${expense.amount:,.2f}"])
    data.append(["", "", "Total", f"${total:,.2f}"])
    table = Table(data, colWidths=[110 * mm, 45 * mm, 35 * mm, 35 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1B4332")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
        ("FONTNAME", (-2, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#F3F4F6")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#F9FAFB")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    generated_on = timezone.localtime().strftime("%Y-%m-%d %H:%M")

    def draw_footer(canvas, doc):
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#D1D5DB"))
        canvas.line(15 * mm, 13 * mm, landscape(A4)[0] - 15 * mm, 13 * mm)
        canvas.setFillColor(colors.HexColor("#6B7280"))
        canvas.setFont("Helvetica", 8)
        x = 15 * mm
        y = 8 * mm
        prefix = f"Generated by {APP_NAME} · Developed by "
        canvas.drawString(x, y, prefix)
        name_x = x + canvas.stringWidth(prefix, "Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#1B4332"))
        canvas.drawString(name_x, y, CREATOR_NAME)
        name_width = canvas.stringWidth(CREATOR_NAME, "Helvetica", 8)
        canvas.linkURL(GITHUB_URL, (name_x, y - 1, name_x + name_width, y + 8), relative=0)
        canvas.setFillColor(colors.HexColor("#6B7280"))
        canvas.drawString(name_x + name_width, y, f" · {generated_on}")
        canvas.drawRightString(landscape(A4)[0] - 15 * mm, 8 * mm, f"Page {doc.page}")
        canvas.restoreState()

    document.build(story, onFirstPage=draw_footer, onLaterPages=draw_footer)
    return output.getvalue()
